### ISSUE TITLE
Chunk 6

### ISSUE THREAD

**Issue by dossorio** [dossorio/google-interview-university#4]
- [x] ~~Pick One Language for the Interview~~ Issue #29 Implemented #28 
- [ ] Book List
- [ ] ~~Before you Get Started~~ #31 
- [ ] ~~What you Won't See Covered~~ #31

**Comment by sjaramillo10** [comment]
I am taking this one, just one thing. This is my first time contributing in GitHub so I don't know how to do many things. If I do something wrong just let me know please. Also I am from Mexico, not sure where you are from but you translate some words different than me so you must be from another country. Argentina maybe?

**Comment by dossorio** [comment]
Ok ! This is issue is yours then. :)

Everything is going ok ! You are doing like an expert ! I am learning too ;)

Yes I am from Spain, there should be some differences but nothing we could not deal with ;), if you find anything that its wrong or anything that can be better expressed differently, please feel free to modify it !

I see you around, Cheers !
